const data = {
  products: [
    {
      id: 1,
      name: "Chocolate Truffles",
      slug: "chocolate-truffles",
      image: "images/product-1.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: 150000,
      price: 100000,
      productType: "sale",
      inventory: 10,
    },
    {
      id: 2,
      name: "Milk Chocolate",
      slug: "milk-chocolate",
      image: "images/product-2.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: "",
      price: 200000,
      productType: "",
      inventory: 8,
    },
    {
      id: 3,
      name: "Chocolate Van",
      slug: "chocolate-van",
      image: "images/product-3.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: "",
      price: 300000,
      productType: "new",
      inventory: 9,
    },
    {
      id: 4,
      name: "Cookies",
      slug: "cookies",
      image: "images/product-4.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: "",
      price: 30000,
      productType: "",
      inventory: 12,
    },
    {
      id: 5,
      name: "Truffles",
      slug: "truffles",
      image: "images/product-3.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: 350000,
      price: 50000,
      productType: "",
      inventory: 15,
    },
    {
      id: 6,
      name: "Chocolate Pudding",
      slug: "chocolate-pudding",
      image: "images/product-4.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: 300000,
      price: 250000,
      productType: "new",
      inventory: 3,
    },
    {
      id: 7,
      name: "Dark Chocolate",
      slug: "dark-chocolate",
      image: "/images/product-1.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: 400000,
      price: 300000,
      productType: "",
      inventory: 5,
    },
    {
      id: 8,
      name: "Chocolate Cookies",
      slug: "chocolate-cookies",
      image: "images/product-2.png",
      descriptions: "Lorem ipsum dolor sit amet consectetur adipisicing",
      priceOld: "",
      price: 300000,
      productType: "",
      inventory: 10,
    },
  ],
};
export default data;
